// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_json`, `span_json`

/// Сканировать каталог и вернуть модули .sb, которые открываются.
/// Битые и посторонние файлы пропускаются — они не должны ронять UI.
Future<List<ModuleInfo>> listModules({required String dir}) =>
    RustLib.instance.api.crateApiModuleListModules(dir: dir);

/// Документ модуля в формате export.rs, но без глав: `chapters` пуст —
/// их UI подтягивает лениво через [`chapter_doc`].
Future<String> moduleDoc({required String path}) =>
    RustLib.instance.api.crateApiModuleModuleDoc(path: path);

/// Глава в формате export.rs: `{"n":..,"blocks":[..]}`.
/// `None`, если такой главы в модуле нет.
Future<String?> chapterDoc({
  required String path,
  required String book,
  required PlatformInt64 chapter,
}) => RustLib.instance.api.crateApiModuleChapterDoc(
  path: path,
  book: book,
  chapter: chapter,
);

/// Искать в модуле. `cache_path` — файл индекса рядом с модулем
/// (по соглашению CLI — `<module>.idx`); при несовпадении ключа
/// индекс перестраивается автоматически.
Future<List<SearchHitInfo>> moduleSearch({
  required String modulePath,
  required String cachePath,
  required String query,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiModuleModuleSearch(
  modulePath: modulePath,
  cachePath: cachePath,
  query: query,
  limit: limit,
);

/// Модуль .sb, найденный в каталоге данных.
class ModuleInfo {
  /// `meta.id` модуля — ключ выбора в UI (`russyn`, `engwebp`…).
  final String id;
  final String title;

  /// BCP 47 (`ru`, `en`, `he`, `grc`).
  final String language;

  /// Абсолютный путь к файлу .sb.
  final String path;

  const ModuleInfo({
    required this.id,
    required this.title,
    required this.language,
    required this.path,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ language.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          language == other.language &&
          path == other.path;
}

/// Результат поиска для UI (зеркало `store::search::Hit`).
class SearchHitInfo {
  final String book;
  final PlatformInt64 chapter;
  final PlatformInt64 verse;

  /// Фрагмент текста с разметкой выделения совпадения.
  final String snippet;

  const SearchHitInfo({
    required this.book,
    required this.chapter,
    required this.verse,
    required this.snippet,
  });

  @override
  int get hashCode =>
      book.hashCode ^ chapter.hashCode ^ verse.hashCode ^ snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHitInfo &&
          runtimeType == other.runtimeType &&
          book == other.book &&
          chapter == other.chapter &&
          verse == other.verse &&
          snippet == other.snippet;
}
