// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `anchor_at`, `anchor`, `entry_info`, `kind_of`, `open`

/// Снять состояние прогресса одним JSON:
/// `{"read":["GEN:1",...], "last_position":"GEN:1"|null, "last_verse":{"GEN:1":5}}`.
Future<String> progressLoad({required String path}) =>
    RustLib.instance.api.crateApiUserdataProgressLoad(path: path);

/// Отметить главу прочитанной (повторная отметка — не дубль).
Future<void> progressMarkRead({
  required String path,
  required String book,
  required PlatformInt64 chapter,
}) => RustLib.instance.api.crateApiUserdataProgressMarkRead(
  path: path,
  book: book,
  chapter: chapter,
);

/// «Продолжить отсюда»: одна запись-позиция на всю базу.
Future<void> progressSetPosition({
  required String path,
  required String book,
  required PlatformInt64 chapter,
  required PlatformInt64 verse,
}) => RustLib.instance.api.crateApiUserdataProgressSetPosition(
  path: path,
  book: book,
  chapter: chapter,
  verse: verse,
);

/// Последний открытый стих главы (для автоскролла при возврате).
Future<void> progressSetVerse({
  required String path,
  required String book,
  required PlatformInt64 chapter,
  required PlatformInt64 verse,
}) => RustLib.instance.api.crateApiUserdataProgressSetVerse(
  path: path,
  book: book,
  chapter: chapter,
  verse: verse,
);

/// Сбросить весь прогресс (кнопка «Сбросить» в настройках).
/// Трогает только служебные записи псевдо-модуля — пользовательские не затрагиваются.
Future<void> progressReset({required String path}) =>
    RustLib.instance.api.crateApiUserdataProgressReset(path: path);

/// Записи одного вида; `module: None` — по всем модулям.
Future<List<UserEntryInfo>> entriesList({
  required String path,
  required String kind,
  String? module,
}) => RustLib.instance.api.crateApiUserdataEntriesList(
  path: path,
  kind: kind,
  module: module,
);

/// Добавить запись к стиху модуля; возвращает id записи.
Future<String> entryAdd({
  required String path,
  required String kind,
  required String module,
  required String book,
  required PlatformInt64 chapter,
  required PlatformInt64 verse,
  required String text,
  required String context,
}) => RustLib.instance.api.crateApiUserdataEntryAdd(
  path: path,
  kind: kind,
  module: module,
  book: book,
  chapter: chapter,
  verse: verse,
  text: text,
  context: context,
);

/// Обновить текст записи по id (`false` — записи нет).
Future<bool> entryUpdate({
  required String path,
  required String id,
  required String text,
}) => RustLib.instance.api.crateApiUserdataEntryUpdate(
  path: path,
  id: id,
  text: text,
);

/// Удалить запись по id (`false` — записи нет).
Future<bool> entryRemove({required String path, required String id}) =>
    RustLib.instance.api.crateApiUserdataEntryRemove(path: path, id: id);

/// Запись пользователя для UI — `store::Entry` в простых типах,
/// чтобы Dart-сторона не тянула serde_json по каждой записи.
class UserEntryInfo {
  final String id;

  /// `meta.id` модуля, к которому привязана запись.
  final String module;

  /// `"note" | "mark" | "hl"` (`Kind::as_str`).
  final String kind;
  final String book;
  final PlatformInt64 chapter;
  final PlatformInt64 verse;

  /// Текст заметки, подпись закладки или цвет выделения.
  final String text;

  /// Контрольный фрагмент стиха для перепривязки при обновлении модуля.
  final String context;

  /// Unix-миллисекунды.
  final PlatformInt64 created;
  final PlatformInt64 updated;

  const UserEntryInfo({
    required this.id,
    required this.module,
    required this.kind,
    required this.book,
    required this.chapter,
    required this.verse,
    required this.text,
    required this.context,
    required this.created,
    required this.updated,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      module.hashCode ^
      kind.hashCode ^
      book.hashCode ^
      chapter.hashCode ^
      verse.hashCode ^
      text.hashCode ^
      context.hashCode ^
      created.hashCode ^
      updated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserEntryInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          module == other.module &&
          kind == other.kind &&
          book == other.book &&
          chapter == other.chapter &&
          verse == other.verse &&
          text == other.text &&
          context == other.context &&
          created == other.created &&
          updated == other.updated;
}
