// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `gunzip`

/// Инициализировать акцентор байтами модели и словарей
/// (`accent.onnx`, `vocab.txt`, `yo_words.tsv.gz`, `lexicon.tsv.gz`).
Future<void> accentInit({
  required List<int> model,
  required String vocab,
  required List<int> yoGz,
  required List<int> lexiconGz,
}) => RustLib.instance.api.crateApiVoiceAccentInit(
  model: model,
  vocab: vocab,
  yoGz: yoGz,
  lexiconGz: lexiconGz,
);

/// Текст с ударениями U+0301 и ё по словарю. Без инициализации
/// (ассеты не загрузились) или при ошибке — текст как есть.
Future<String> accentText({required String text}) =>
    RustLib.instance.api.crateApiVoiceAccentText(text: text);
