// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/module.dart';
import 'api/userdata.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -582272648;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'studybible_flutter_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String?> crateApiModuleChapterDoc({
    required String path,
    required String book,
    required PlatformInt64 chapter,
  });

  Future<List<UserEntryInfo>> crateApiUserdataEntriesList({
    required String path,
    required String kind,
    String? module,
  });

  Future<String> crateApiUserdataEntryAdd({
    required String path,
    required String kind,
    required String module,
    required String book,
    required PlatformInt64 chapter,
    required PlatformInt64 verse,
    required String text,
    required String context,
  });

  Future<bool> crateApiUserdataEntryRemove({
    required String path,
    required String id,
  });

  Future<bool> crateApiUserdataEntryUpdate({
    required String path,
    required String id,
    required String text,
  });

  Future<void> crateApiInitApp();

  Future<List<ModuleInfo>> crateApiModuleListModules({required String dir});

  Future<String> crateApiModuleModuleDoc({required String path});

  Future<List<SearchHitInfo>> crateApiModuleModuleSearch({
    required String modulePath,
    required String cachePath,
    required String query,
    required PlatformInt64 limit,
  });

  Future<String> crateApiUserdataProgressLoad({required String path});

  Future<void> crateApiUserdataProgressMarkRead({
    required String path,
    required String book,
    required PlatformInt64 chapter,
  });

  Future<void> crateApiUserdataProgressReset({required String path});

  Future<void> crateApiUserdataProgressSetPosition({
    required String path,
    required String book,
    required PlatformInt64 chapter,
    required PlatformInt64 verse,
  });

  Future<void> crateApiUserdataProgressSetVerse({
    required String path,
    required String book,
    required PlatformInt64 chapter,
    required PlatformInt64 verse,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String?> crateApiModuleChapterDoc({
    required String path,
    required String book,
    required PlatformInt64 chapter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(book, serializer);
          sse_encode_i_64(chapter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleChapterDocConstMeta,
        argValues: [path, book, chapter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleChapterDocConstMeta => const TaskConstMeta(
    debugName: "chapter_doc",
    argNames: ["path", "book", "chapter"],
  );

  @override
  Future<List<UserEntryInfo>> crateApiUserdataEntriesList({
    required String path,
    required String kind,
    String? module,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(kind, serializer);
          sse_encode_opt_String(module, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_user_entry_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUserdataEntriesListConstMeta,
        argValues: [path, kind, module],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserdataEntriesListConstMeta =>
      const TaskConstMeta(
        debugName: "entries_list",
        argNames: ["path", "kind", "module"],
      );

  @override
  Future<String> crateApiUserdataEntryAdd({
    required String path,
    required String kind,
    required String module,
    required String book,
    required PlatformInt64 chapter,
    required PlatformInt64 verse,
    required String text,
    required String context,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(kind, serializer);
          sse_encode_String(module, serializer);
          sse_encode_String(book, serializer);
          sse_encode_i_64(chapter, serializer);
          sse_encode_i_64(verse, serializer);
          sse_encode_String(text, serializer);
          sse_encode_String(context, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUserdataEntryAddConstMeta,
        argValues: [path, kind, module, book, chapter, verse, text, context],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserdataEntryAddConstMeta => const TaskConstMeta(
    debugName: "entry_add",
    argNames: [
      "path",
      "kind",
      "module",
      "book",
      "chapter",
      "verse",
      "text",
      "context",
    ],
  );

  @override
  Future<bool> crateApiUserdataEntryRemove({
    required String path,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUserdataEntryRemoveConstMeta,
        argValues: [path, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserdataEntryRemoveConstMeta =>
      const TaskConstMeta(debugName: "entry_remove", argNames: ["path", "id"]);

  @override
  Future<bool> crateApiUserdataEntryUpdate({
    required String path,
    required String id,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(id, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUserdataEntryUpdateConstMeta,
        argValues: [path, id, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserdataEntryUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "entry_update",
        argNames: ["path", "id", "text"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<ModuleInfo>> crateApiModuleListModules({required String dir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_module_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleListModulesConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleListModulesConstMeta =>
      const TaskConstMeta(debugName: "list_modules", argNames: ["dir"]);

  @override
  Future<String> crateApiModuleModuleDoc({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleModuleDocConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleModuleDocConstMeta =>
      const TaskConstMeta(debugName: "module_doc", argNames: ["path"]);

  @override
  Future<List<SearchHitInfo>> crateApiModuleModuleSearch({
    required String modulePath,
    required String cachePath,
    required String query,
    required PlatformInt64 limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modulePath, serializer);
          sse_encode_String(cachePath, serializer);
          sse_encode_String(query, serializer);
          sse_encode_i_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_hit_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModuleModuleSearchConstMeta,
        argValues: [modulePath, cachePath, query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModuleModuleSearchConstMeta => const TaskConstMeta(
    debugName: "module_search",
    argNames: ["modulePath", "cachePath", "query", "limit"],
  );

  @override
  Future<String> crateApiUserdataProgressLoad({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUserdataProgressLoadConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserdataProgressLoadConstMeta =>
      const TaskConstMeta(debugName: "progress_load", argNames: ["path"]);

  @override
  Future<void> crateApiUserdataProgressMarkRead({
    required String path,
    required String book,
    required PlatformInt64 chapter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(book, serializer);
          sse_encode_i_64(chapter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUserdataProgressMarkReadConstMeta,
        argValues: [path, book, chapter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserdataProgressMarkReadConstMeta =>
      const TaskConstMeta(
        debugName: "progress_mark_read",
        argNames: ["path", "book", "chapter"],
      );

  @override
  Future<void> crateApiUserdataProgressReset({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUserdataProgressResetConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserdataProgressResetConstMeta =>
      const TaskConstMeta(debugName: "progress_reset", argNames: ["path"]);

  @override
  Future<void> crateApiUserdataProgressSetPosition({
    required String path,
    required String book,
    required PlatformInt64 chapter,
    required PlatformInt64 verse,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(book, serializer);
          sse_encode_i_64(chapter, serializer);
          sse_encode_i_64(verse, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUserdataProgressSetPositionConstMeta,
        argValues: [path, book, chapter, verse],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserdataProgressSetPositionConstMeta =>
      const TaskConstMeta(
        debugName: "progress_set_position",
        argNames: ["path", "book", "chapter", "verse"],
      );

  @override
  Future<void> crateApiUserdataProgressSetVerse({
    required String path,
    required String book,
    required PlatformInt64 chapter,
    required PlatformInt64 verse,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(book, serializer);
          sse_encode_i_64(chapter, serializer);
          sse_encode_i_64(verse, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUserdataProgressSetVerseConstMeta,
        argValues: [path, book, chapter, verse],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserdataProgressSetVerseConstMeta =>
      const TaskConstMeta(
        debugName: "progress_set_verse",
        argNames: ["path", "book", "chapter", "verse"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<ModuleInfo> dco_decode_list_module_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_module_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SearchHitInfo> dco_decode_list_search_hit_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_hit_info).toList();
  }

  @protected
  List<UserEntryInfo> dco_decode_list_user_entry_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_user_entry_info).toList();
  }

  @protected
  ModuleInfo dco_decode_module_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ModuleInfo(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      language: dco_decode_String(arr[2]),
      path: dco_decode_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SearchHitInfo dco_decode_search_hit_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchHitInfo(
      book: dco_decode_String(arr[0]),
      chapter: dco_decode_i_64(arr[1]),
      verse: dco_decode_i_64(arr[2]),
      snippet: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UserEntryInfo dco_decode_user_entry_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return UserEntryInfo(
      id: dco_decode_String(arr[0]),
      module: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      book: dco_decode_String(arr[3]),
      chapter: dco_decode_i_64(arr[4]),
      verse: dco_decode_i_64(arr[5]),
      text: dco_decode_String(arr[6]),
      context: dco_decode_String(arr[7]),
      created: dco_decode_i_64(arr[8]),
      updated: dco_decode_i_64(arr[9]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<ModuleInfo> sse_decode_list_module_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModuleInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_module_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SearchHitInfo> sse_decode_list_search_hit_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchHitInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_hit_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<UserEntryInfo> sse_decode_list_user_entry_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UserEntryInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_user_entry_info(deserializer));
    }
    return ans_;
  }

  @protected
  ModuleInfo sse_decode_module_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    return ModuleInfo(
      id: var_id,
      title: var_title,
      language: var_language,
      path: var_path,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SearchHitInfo sse_decode_search_hit_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_book = sse_decode_String(deserializer);
    var var_chapter = sse_decode_i_64(deserializer);
    var var_verse = sse_decode_i_64(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    return SearchHitInfo(
      book: var_book,
      chapter: var_chapter,
      verse: var_verse,
      snippet: var_snippet,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UserEntryInfo sse_decode_user_entry_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_module = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_book = sse_decode_String(deserializer);
    var var_chapter = sse_decode_i_64(deserializer);
    var var_verse = sse_decode_i_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_context = sse_decode_String(deserializer);
    var var_created = sse_decode_i_64(deserializer);
    var var_updated = sse_decode_i_64(deserializer);
    return UserEntryInfo(
      id: var_id,
      module: var_module,
      kind: var_kind,
      book: var_book,
      chapter: var_chapter,
      verse: var_verse,
      text: var_text,
      context: var_context,
      created: var_created,
      updated: var_updated,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_module_info(
    List<ModuleInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_module_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_search_hit_info(
    List<SearchHitInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_hit_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_user_entry_info(
    List<UserEntryInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_user_entry_info(item, serializer);
    }
  }

  @protected
  void sse_encode_module_info(ModuleInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_search_hit_info(
    SearchHitInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.book, serializer);
    sse_encode_i_64(self.chapter, serializer);
    sse_encode_i_64(self.verse, serializer);
    sse_encode_String(self.snippet, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user_entry_info(
    UserEntryInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.module, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.book, serializer);
    sse_encode_i_64(self.chapter, serializer);
    sse_encode_i_64(self.verse, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.context, serializer);
    sse_encode_i_64(self.created, serializer);
    sse_encode_i_64(self.updated, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
